# Generated by Django 5.0.4 on 2024-05-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_frequentlyaskquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskQuestion',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
