# Generated by Django 5.0.4 on 2024-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactformlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
